```{r}
library(ISLR2)
```

9)

```{r}
auto = Auto
```

9a) name and cylinders is qualitative, other variables are quantitative

```{r}
colnames(auto)
```

9b)

```{r}
attach(auto)
range(mpg)
range(displacement)
range(horsepower)
range(weight)
range(acceleration)
range(year)
range(origin)
```

9c)

```{r}
attach(auto)
mean(mpg)
mean(displacement)
mean(horsepower)
mean(weight)
mean(acceleration)
mean(year)
mean(origin)
sd(mpg)
sd(displacement)
sd(horsepower)
sd(weight)
sd(acceleration)
sd(year)
sd(origin)
```

9d)

```{r}
autoends = auto[-c(10:85)]
attach(autoends)
range(mpg)
range(displacement)
range(horsepower)
range(weight)
range(acceleration)
range(year)
range(origin)
mean(mpg)
mean(displacement)
mean(horsepower)
mean(weight)
mean(acceleration)
mean(year)
mean(origin)
sd(mpg)
sd(displacement)
sd(horsepower)
sd(weight)
sd(acceleration)
sd(year)
sd(origin)
```

9e)

```{r}
plot(year,mpg)
plot(weight,mpg)
plot(acceleration,mpg)
```

9f) yes, some plots seem to show a relationship with some variables, and mpg

```{r}

```
