```{r}
library(MASS)
library(ISLR2)
rm(list=ls())
```

```{r}
head(Boston)
```

```{r}

lm.fit = lm(medv ~ lstat)

```

```{r}
lm.fit = lm(medv ~ lstat, data = Boston)
attach(Boston)
lm.fit = lm(medv ~ lstat)
```

```{r}
lm.fit

summary(lm.fit)
```

```{r}
names(lm.fit)
```

```{r}
confint(lm.fit)
```

```{r}
predict(lm.fit, data.frame(lstat = (c(5, 10, 15))),
interval = "confidence")
```

```{r}
predict(lm.fit, data.frame(lstat = (c(5, 10, 15))),
interval = "prediction")
```

```{r}
plot(lstat, medv)
abline(lm.fit)
```

```{r}
plot(lstat, medv)
abline(lm.fit, lwd = 3)
abline(lm.fit, lwd = 3, col = "red")
```

```{r}
plot(lstat, medv, col = "red")
plot(lstat, medv, pch = 20)
plot(lstat, medv, pch = "+")
plot(1:20, 1:20, pch = 1:20)

```

```{r}
par(mfrow = c(2, 2))
plot(lm.fit)
```

```{r}
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
```

```{r}
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
```
